worker_processes auto;

events {}

http {
  include       mime.types;  # This line includes the default MIME types
  default_type application/octet-stream;

  server {
    listen 10000;  # Default port; it can be changed later
    
    location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html;
    }
  }
}
